### ISSUE TITLE
Question - Mailboxer.email_method parameters causing ArgumentError: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by bringmebeer** [mailboxer/mailboxer#192]
This is more of a question than an issue, hopefully this is the right place to ask.

app/models/message.rb:45 makes a call to Object.send passing in an optional reference to an instance of the message.

```
email_to = recipient.send(Mailboxer.email_method, self)
```

The message instance is passed as a parameter to the recipients email method in _spec/dummy/app/models/user.rb_, but this object is not required to return the email value.

My User.email method doesn't require any parameters so I get the following  ArgumentError: wrong number of arguments (1 for 0) error when I try and call _user.send_message(recipient, "body", "subject")

```
ArgumentError: wrong number of arguments (1 for 0)
    from /Users/bringmebeer/.rvm/gems/ruby-1.9.3-p125@zapnito/gems/activerecord-3.2.13/lib/active_record/attribute_methods/read.rb:71:in `__temp__'
    from /Users/bringmebeer/.rvm/gems/ruby-1.9.3-p125@zapnito/gems/mailboxer-0.11.0/app/models/message.rb:45:in `block in deliver'
    from /Users/bringmebeer/.rvm/gems/ruby-1.9.3-p125@zapnito/gems/mailboxer-0.11.0/app/models/message.rb:44:in `each'
    from /Users/bringmebeer/.rvm/gems/ruby-1.9.3-p125@zapnito/gems/mailboxer-0.11.0/app/models/message.rb:44:in `deliver'
    from /Users/bringmebeer/.rvm/gems/ruby-1.9.3-p125@zapnito/gems/mailboxer-0.11.0/lib/mailboxer/models/messageable.rb:71:in `send_message'
    from (irb):3
```

My solution to this will be simply to provide a User.mailboxer_email method that wraps my own User.email method.

```
class User < ActiveRecord::Base
    acts_as_messageable

        def mailboxer_email(object)
            return email
        end

        def email
            # return email
        end
end
```

I'm wondering why a the _mailboxer_email(object)_ method takes a parameter at all?  If there is a good reason (which I'm sure there is) maybe it could be more clearly documented within Mailboxer.rb config?

**Comment by 5minpause** [comment]
Thanks for pointing this out. I had the same problem.
