### ISSUE TITLE
ArgumentError: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by juanpastas** [mailboxer/mailboxer#346]
I saw a similar problem at #52.

```
[2] pry(main)> User.first.send_message(User.last, 'body body', 'subject')
  User Load (0.3ms)  SELECT  "users".* FROM "users"   ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.2ms)  SELECT  "users".* FROM "users"   ORDER BY "users"."id" DESC LIMIT 1
   (0.1ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "mailboxer_conversations" ("created_at", "subject", "updated_at") VALUES (?, ?, ?)  [["created_at", "2015-04-07 14:51:42.669433"], ["subject", "subject"], ["updated_at", "2015-04-07 14:51:42.669433"]]
  SQL (0.2ms)  INSERT INTO "mailboxer_notifications" ("body", "conversation_id", "created_at", "sender_id", "sender_type", "subject", "type", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["body", "body body"], ["conversation_id", 9], ["created_at", "2015-04-07 14:51:42.669433"], ["sender_id", 1], ["sender_type", "User"], ["subject", "subject"], ["type", "Mailboxer::Message"], ["updated_at", "2015-04-07 14:51:42.669433"]]
  SQL (0.2ms)  INSERT INTO "mailboxer_receipts" ("created_at", "mailbox_type", "notification_id", "receiver_id", "receiver_type", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["created_at", "2015-04-07 14:51:42.677185"], ["mailbox_type", "inbox"], ["notification_id", 9], ["receiver_id", 2], ["receiver_type", "User"], ["updated_at", "2015-04-07 14:51:42.677185"]]
   (107.2ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "mailboxer_receipts" ("created_at", "is_read", "mailbox_type", "notification_id", "receiver_id", "receiver_type", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["created_at", "2015-04-07 14:51:42.787733"], ["is_read", "t"], ["mailbox_type", "sentbox"], ["notification_id", 9], ["receiver_id", 1], ["receiver_type", "User"], ["updated_at", "2015-04-07 14:51:42.787733"]]
   (113.5ms)  commit transaction
   (0.1ms)  SELECT COUNT(*) FROM "mailboxer_conversation_opt_outs"  WHERE "mailboxer_conversation_opt_outs"."conversation_id" = ? AND "mailboxer_conversation_opt_outs"."unsubscriber_type" = 'User' AND "mailboxer_conversation_opt_outs"."unsubscriber_id" = 2  [["conversation_id", 9]]
ArgumentError: wrong number of arguments (1 for 0)
from /home/pills/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.4/lib/active_record/attribute_methods.rb:45:in `__temp__56d61696c6'

```

Everything is saved correctly but there is an error at the end, here is my config:

```
Mailboxer.setup do |config|

  #Configures if you application uses or not email sending for Notifications and Messages
  config.uses_emails = true

  #Configures the default from for emails sent for Messages and Notifications
  config.default_from = "no-reply@mailboxer.com"

  #Configures the methods needed by mailboxer
  config.email_method = :email
  config.name_method = :name

  #Configures if you use or not a search engine and which one you are using
  #Supported engines: [:solr,:sphinx]
  config.search_enabled = false
  # config.search_engine = :solr

  #Configures maximum length of the message subject and body
  config.subject_max_length = 255
  config.body_max_length = 32000
end

```

And my model:

```
class User < ActiveRecord::Base
  acts_as_messageable

  ...
```

User model has name and email methods:

```
[3] pry(main)> User.first.name
  User Load (0.2ms)  SELECT  "users".* FROM "users"   ORDER BY "users"."id" ASC LIMIT 1
=> "Juan David Pastás"
[4] pry(main)> User.first.email
  User Load (0.4ms)  SELECT  "users".* FROM "users"   ORDER BY "users"."id" ASC LIMIT 1
=> "pastasjuan@gmail.com"
```

**Comment by juanpastas** [comment]
This is part of the trace:

```
/home/pills/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.4/lib/active_record/attribute_methods.rb:45:in `__temp__56d61696c6'
/home/pills/.rvm/gems/ruby-2.1.2/gems/mailboxer-0.12.5/lib/mailboxer/mail_dispatcher.rb:16:in `block in call'
/home/pills/.rvm/gems/ruby-2.1.2/gems/mailboxer-0.12.5/lib/mailboxer/mail_dispatcher.rb:15:in `each'
/home/pills/.rvm/gems/ruby-2.1.2/gems/mailboxer-0.12.5/lib/mailboxer/mail_dispatcher.rb:15:in `call'
/home/pills/.rvm/gems/ruby-2.1.2/gems/mailboxer-0.12.5/app/models/mailboxer/message.rb:38:in `deliver'
/home/pills/.rvm/gems/ruby-2.1.2/gems/mailboxer-0.12.5/lib/mailboxer/models/messageable.rb:83:in `send_message'
```

It says `email_to = recipient.send(Mailboxer.email_method, mailable)`.

**Comment by gls2ro** [comment]
Hey,

I have the same error. 

I'm adding more info to what @juanpastas posted. 

```
[3] pry(main)> t.send_message( p, "Test", "test")
   (0.2ms)  begin transaction
  SQL (0.7ms)  INSERT INTO "mailboxer_conversations" ("created_at", "subject", "updated_at") VALUES (?, ?, ?)  [["created_at", "2015-04-28 14:53:36.844851"], ["subject", "test"], ["updated_at", "2015-04-28 14:53:36.844851"]]
  SQL (0.4ms)  INSERT INTO "mailboxer_notifications" ("body", "conversation_id", "created_at", "sender_id", "sender_type", "subject", "type", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["body", "Test"], ["conversation_id", 4], ["created_at", "2015-04-28 14:53:36.844851"], ["sender_id", 1], ["sender_type", "Trainer"], ["subject", "test"], ["type", "Mailboxer::Message"], ["updated_at", "2015-04-28 14:53:36.844851"]]
  SQL (0.3ms)  INSERT INTO "mailboxer_receipts" ("created_at", "mailbox_type", "notification_id", "receiver_id", "receiver_type", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["created_at", "2015-04-28 14:53:37.069388"], ["mailbox_type", "inbox"], ["notification_id", 4], ["receiver_id", 1], ["receiver_type", "Trainee"], ["updated_at", "2015-04-28 14:53:37.069388"]]
   (1.5ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.5ms)  INSERT INTO "mailboxer_receipts" ("created_at", "is_read", "mailbox_type", "notification_id", "receiver_id", "receiver_type", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["created_at", "2015-04-28 14:53:37.075487"], ["is_read", "t"], ["mailbox_type", "sentbox"], ["notification_id", 4], ["receiver_id", 1], ["receiver_type", "Trainer"], ["updated_at", "2015-04-28 14:53:37.075487"]]
   (1.0ms)  commit transaction
   (0.2ms)  SELECT COUNT(*) FROM "mailboxer_conversation_opt_outs"  WHERE "mailboxer_conversation_opt_outs"."conversation_id" = ? AND "mailboxer_conversation_opt_outs"."unsubscriber_type" = 'Trainee' AND "mailboxer_conversation_opt_outs"."unsubscriber_id" = 1  [["conversation_id", 4]]
ArgumentError: wrong number of arguments (1 for 0)
from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods.rb:45:in `__temp__56d61696c6'
```

And my config is:
```
Mailboxer.setup do |config|

  #Configures if you application uses or not email sending for Notifications and Messages
  config.uses_emails = true 

  #Configures the default from for emails sent for Messages and Notifications
  config.default_from = "no-reply@mailboxer.com"

  #Configures the methods needed by mailboxer
  config.email_method = :email
  config.name_method = :name

  #Configures if you use or not a search engine and which one you are using
  #Supported engines: [:solr,:sphinx]
  config.search_enabled = false
  config.search_engine = :solr

  #Configures maximum length of the message subject and body
  config.subject_max_length = 255
  config.body_max_length = 32000
end
```

And I think the error is somehow related to email sending because I did some tests and it appears only when _config.uses_emails_ is set to _true_. If you don't use emails then you don't get this error.

**Comment by juanpastas** [comment]
In my  case I needed to create a mail method with argument.

```
def mailboxer_email(messageable)
  email
end
```

You might not use messageable argument.

**Comment by gls2ro** [comment]
@juanpastas thank you. 
Yes, didn't read carefully the specification and didn't saw the argument for mailboxer_email

**Comment by lsaffie** [comment]
@juanpastas thanks!
