### ISSUE TITLE
Is there a way to limit and validate the attachment size?

### ISSUE THREAD

**Issue by jplethier** [mailboxer/mailboxer#363]
I need to validate the attachment size, because I don't want to let my users to upload large files, is there a way to do this on mailboxer?

**Comment by onlinetocode** [comment]
Hi @jplethier, mailboxer uses [carrierwave](https://github.com/carrierwaveuploader/carrierwave) for processing attachments. 

Just for your information: you could find the uploader class here: [AttachmentUploader](https://github.com/mailboxer/mailboxer/blob/51fd6391592aace8a8eb3d1b1a761a9bea81fe1b/app/uploaders/mailboxer/attachment_uploader.rb)
```ruby
class Mailboxer::AttachmentUploader < CarrierWave::Uploader::Base
  storage :file
end
```
To validate the attachment size, you could open the Mailboxer::Message class and add a custom validator.
You could try to add an initializer file like `message_attachment_validator.rb` to the `config/initializers` folder with the following code:
```ruby
class Mailboxer::Message < Mailboxer::Notification
  validates :logo, 
    :file_size => { 
      :maximum => 5.megabytes.to_i 
    } 
end
```
Here you could find information about validation of attachments processed by carrierwave: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Validate-attachment-file-size.

**Comment by SubhashShah-BTC** [comment]
After modifying the `Mailboxer::Message` model in `config/initializers/message_attachment_validator.rb` and enabling the `file_size_validator.rb` , I am getting following error:

```
NoMethodError - undefined method `conversation=' for #<Mailboxer::Message:0xb509d890>:
  activemodel (4.2.2) lib/active_model/attribute_methods.rb:433:in `method_missing'
   () home/test/.rvm/gems/ruby-2.2.1/bundler/gems/mailboxer-d4f0e9c70e29/app/builders/mailboxer/base_builder.rb:12:in `block (2 levels) in build'
   () home/test/.rvm/gems/ruby-2.2.1/bundler/gems/mailboxer-d4f0e9c70e29/app/builders/mailboxer/base_builder.rb:11:in `block in build'
   () home/test/.rvm/gems/ruby-2.2.1/bundler/gems/mailboxer-d4f0e9c70e29/app/builders/mailboxer/base_builder.rb:10:in `build'
   () home/test/.rvm/gems/ruby-2.2.1/bundler/gems/mailboxer-d4f0e9c70e29/lib/mailboxer/models/messageable.rb:81:in `send_message'
```

The code in the modified `Message` model is as below.
```ruby
require 'file_size_validator'

class Mailboxer::Message < Mailboxer::Notification
  validates :attachment, file_size: { maximum: 5.megabytes }
end
```

Am I missing something?

**Comment by jplethier** [comment]
@onlinetocode sorry for the delay, I left the project where I was using the mailboxer gem, but thanks for the answer anyway

**Comment by EnziinSystem** [comment]
Hi,

You can use jQuery to check the file before upload.

http://stackoverflow.com/a/22879615/7598242
