### ISSUE TITLE
Rails 5.0.0: Unknown key: :order

### ISSUE THREAD

**Issue by knightq** [mailboxer/mailboxer#427]
ruby: ruby 2.3.1p112
rails: Rails 5.0.0
mailboxer: 0.13.0

Rails 5.0.0 fails on startup with this error:

```bash
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/hash/keys.rb:79:in `block in assert_valid_keys': Unknown key: :order. Valid keys are: :class_name, :anonymous_class, :foreign_key, :vali
date, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors (ArgumentError)
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/hash/keys.rb:77:in `each_key'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/hash/keys.rb:77:in `assert_valid_keys'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/builder/association.rb:78:in `validate_options'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/builder/association.rb:44:in `create_reflection'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/builder/association.rb:29:in `build'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations.rb:1360:in `has_many'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailboxer-0.13.0/lib/mailboxer/models/messageable.rb:21:in `block in <module:Messageable>'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `class_eval'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `append_features'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailboxer-0.13.0/lib/mailboxer/models/messageable.rb:10:in `include'
        from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailboxer-0.13.0/lib/mailboxer/models/messageable.rb:10:in `acts_as_messageable'
        from ~/Development/epersonam/app/models/user.rb:34:in `<class:User>'
```

**Comment by knightq** [comment]
[This answer on StackOverflow](http://stackoverflow.com/questions/37378329/server-exiting-after-upgrading-to-rails-5-0-0-rc1-from-rails-4-2-6) suggested me to change the Gemfile requirement from the latest version to the master branch.

This hint worked for me, but:

1. It should be documented the in the README
2. A new tag version should be made ASAP

Thank you

**Comment by deivid-rodriguez** [comment]
There's already a new tag released supporting Rails 5. Can be closed.
