### ISSUE TITLE
wrong number of parameters both for send_message and reply_to_conversation

### ISSUE THREAD

**Issue by arael** [mailboxer/mailboxer#466]
Hi,
I am not able to make the reply_to_conversation work no matter what I do.
Here is the output. In the log a and b are of type User, which uses mailboxer.
The weird part is that send_message raises the error but the message ends up in the receivers inbox.

`
irb(main):006:0> g.send_message a, 'ciao admin this doesnt work', 'sucks'
   (0.3ms)  BEGIN
  SQL (0.4ms)  INSERT INTO "mailboxer_conversations" ("subject", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["subject", "sucks"], ["created_at", "2017-06-26 19:37:14.687053"], ["updated_at", "2017-06-26 19:37:14.687053"]]
  SQL (0.7ms)  INSERT INTO "mailboxer_notifications" ("type", "body", "subject", "sender_type", "sender_id", "conversation_id", "updated_at", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["type", "Mailboxer::Message"], ["body", "ciao admin this doesnt work"], ["subject", "sucks"], ["sender_type", "User"], ["sender_id", 2], ["conversation_id", 4], ["updated_at", "2017-06-26 19:37:14.687053"], ["created_at", "2017-06-26 19:37:14.687053"]]
  SQL (0.6ms)  INSERT INTO "mailboxer_receipts" ("receiver_type", "receiver_id", "notification_id", "mailbox_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["receiver_type", "User"], ["receiver_id", 1], ["notification_id", 4], ["mailbox_type", "inbox"], ["created_at", "2017-06-26 19:37:14.763797"], ["updated_at", "2017-06-26 19:37:14.763797"]]
  SQL (0.4ms)  INSERT INTO "mailboxer_receipts" ("receiver_type", "receiver_id", "notification_id", "is_read", "mailbox_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["receiver_type", "User"], ["receiver_id", 2], ["notification_id", 4], ["is_read", "t"], ["mailbox_type", "sentbox"], ["created_at", "2017-06-26 19:37:14.765411"], ["updated_at", "2017-06-26 19:37:14.765411"]]
   (3.2ms)  COMMIT
ArgumentError: wrong number of arguments (given 1, expected 0)
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.3/lib/active_record/attribute_methods/read.rb:34:in `__temp__56d61696c6'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/lib/mailboxer/mail_dispatcher.rb:13:in `block in call'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/lib/mailboxer/mail_dispatcher.rb:12:in `map'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/lib/mailboxer/mail_dispatcher.rb:12:in `call'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/app/models/mailboxer/message.rb:39:in `deliver'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/lib/mailboxer/models/messageable.rb:78:in `send_message'
	from (irb):6
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/console.rb:65:in `start'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):007:0> a.reply_to_conversation a.mailbox.inbox.first, 'this is my reply'
  Mailboxer::Conversation Load (1.6ms)  SELECT  DISTINCT "mailboxer_conversations".* FROM "mailboxer_conversations" INNER JOIN "mailboxer_notifications" ON "mailboxer_notifications"."conversation_id" = "mailboxer_conversations"."id" AND "mailboxer_notifications"."type" IN ('Mailboxer::Message') INNER JOIN "mailboxer_receipts" ON "mailboxer_receipts"."notification_id" = "mailboxer_notifications"."id" WHERE "mailboxer_notifications"."type" = $1 AND "mailboxer_receipts"."receiver_id" = $2 AND "mailboxer_receipts"."receiver_type" = $3 AND "mailboxer_receipts"."mailbox_type" = $4 AND "mailboxer_receipts"."trashed" = $5 AND "mailboxer_receipts"."deleted" = $6 ORDER BY "mailboxer_conversations"."updated_at" DESC LIMIT $7  [["type", "Mailboxer::Message"], ["receiver_id", 1], ["receiver_type", "User"], ["mailbox_type", "inbox"], ["trashed", "f"], ["deleted", "f"], ["LIMIT", 1]]
   (0.7ms)  SELECT COUNT(*) FROM "mailboxer_receipts" INNER JOIN "mailboxer_notifications" ON "mailboxer_notifications"."id" = "mailboxer_receipts"."notification_id" AND "mailboxer_notifications"."type" IN ('Mailboxer::Message') WHERE "mailboxer_notifications"."conversation_id" = $1 AND "mailboxer_receipts"."receiver_id" = $2 AND "mailboxer_receipts"."receiver_type" = $3 AND "mailboxer_receipts"."trashed" = $4 AND "mailboxer_receipts"."deleted" = $5  [["conversation_id", 4], ["receiver_id", 1], ["receiver_type", "User"], ["trashed", "t"], ["deleted", "f"]]
  Mailboxer::Message Load (0.6ms)  SELECT  "mailboxer_notifications".* FROM "mailboxer_notifications" WHERE "mailboxer_notifications"."type" IN ('Mailboxer::Message') AND "mailboxer_notifications"."conversation_id" = $1 ORDER BY "mailboxer_notifications"."created_at" DESC, "mailboxer_notifications"."id" DESC LIMIT $2  [["conversation_id", 4], ["LIMIT", 1]]
  Mailboxer::Receipt Load (0.4ms)  SELECT "mailboxer_receipts".* FROM "mailboxer_receipts" WHERE "mailboxer_receipts"."notification_id" = $1  [["notification_id", 4]]
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (1, 2)
   (0.7ms)  SELECT COUNT(*) FROM "mailboxer_conversation_opt_outs" WHERE "mailboxer_conversation_opt_outs"."conversation_id" = $1 AND "mailboxer_conversation_opt_outs"."unsubscriber_type" = $2 AND "mailboxer_conversation_opt_outs"."unsubscriber_id" = $3  [["conversation_id", 4], ["unsubscriber_type", "User"], ["unsubscriber_id", 1]]
   (0.5ms)  SELECT COUNT(*) FROM "mailboxer_conversation_opt_outs" WHERE "mailboxer_conversation_opt_outs"."conversation_id" = $1 AND "mailboxer_conversation_opt_outs"."unsubscriber_type" = $2 AND "mailboxer_conversation_opt_outs"."unsubscriber_id" = $3  [["conversation_id", 4], ["unsubscriber_type", "User"], ["unsubscriber_id", 2]]
ArgumentError: wrong number of arguments (given 6, expected 1)
	from /home/arael/workspace/programship/app/models/user.rb:202:in `reply'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mailboxer-0.15.1/lib/mailboxer/models/messageable.rb:117:in `reply_to_conversation'
	from (irb):7
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/console.rb:65:in `start'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/arael/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

`

**Comment by bellef** [comment]
Same test and same output here.

**Comment by antislice** [comment]
I just ran into the same thing when I enabled sending emails, or at least I got @arael's top stack trace when I try `reply_to_conversation`. The line in mailboxer that seems to break is `/mailboxer/mail_dispatcher.rb:13`, 
```
email_to = receipt.receiver.send(Mailboxer.email_method, mailable)
```
`receiver` is the messageable, the user, and `Mailboxer.email_method` is (for me) `User.email`. `mailable` is the message that Mailboxer is trying to send an email about. Given that the variable getting assigned is called `email_to`, I think this is trying to get the email address to send to. However, the `email` method on my User model does not accept params, and I'd assume most people's models don't since that would be an attribute getter.

The emails sent appropriately if I removed the 2nd argument from the method call there and in `message_mailer.rb`.

**Comment by antislice** [comment]
Went back to the readme, and this is apparently expected. The `email` method is supposed to check if an email should be sent, and only return the email address if so. @arael and @bellef I'd check whatever method you have configured as the `email_method`.

**Comment by bellef** [comment]
Thank you for searching about this issue @antislice 
In the end, I've done something from scratch because I didn't need the whole gem here.

**Comment by arael** [comment]
Same here @antislice. Thank you very much for the answer but I also have written something from scratch in the end.
